### ISSUE TITLE
loadbefore と loadafter を使いこなせてない説

### ISSUE THREAD

**Issue by lesguillemets** [lesguillemets/myvim#35]
``` yaml
  parsonsmatt/vim2hs:
    filetype: haskell
    loadafter: haskell-indent
    before: |
      let g:haskell_conceal_enumerations=0
      let g:haskell_conceal_wide=0
      let g:haskell_fold = 0

  itchyny/vim-haskell-indent:
    filetype: haskell
    loadbefore: vim2hs

```

が効いてない
